video_paths = [
    '/home/geuba03p/results/droso_18deg_20251002_102448_arena_02.mp4',
]
intensity_ths = [0, 122]
area_ths = [50.0, inf]
tracking_intervals = ""
number_of_animals = 3
use_bkg = false
check_segmentation = false
track_wo_identities = false
roi_list = ""
