video_paths = [
    '/home/geuba03p/cca_movies/droso_18deg_20251002_102448_arena_08.mp4',
]
intensity_ths = [0, 127]
area_ths = [50, 4000]
tracking_intervals = ""
number_of_animals = 3
use_bkg = false
check_segmentation = false
track_wo_identities = false
roi_list = ""
